apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
#  namespace: monitoring
#  annotations:
#    kubernetes.io/tls-acme="true"
#    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: wordpress 
    servicePort: 80
